include: package:flutter_lints/flutter.yaml


analyzer:
  errors:
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
    unused_import: warning
    dead_code: warning
    super_formal_parameter_without_associated_named: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_single_quotes: true
    always_use_package_imports: true