name: prokat_app
description: Fresh Flutter starter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  image_picker: ^1.1.2

  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4

  dio: ^5.4.3+1
  flutter_secure_storage: ^9.0.0
  mask_text_input_formatter: ^2.4.0
  pin_code_fields: ^8.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
